export type Starship = {
  name: string,
  model: string,
  manufacturer: string,
  constInCredits: string,
  length: string,
  maxAtmospheringSpeed: string,
  crew: string,
  passengers: string,
  cargoCapacity: string,
  consumables: string,
  hyperdriveRating: string,
  mglt: string,
  starshipClass: string,
  pilots: string[],
  films: number[],
  created: string,
  edited: string,
  url: string,
}